### ISSUE TITLE
Documentation outdated for concourse version 3.9.2

### ISSUE THREAD

**Issue by avirkar** [pivotal-cf/docs-concourse-olm#10]
I think this documentation is outdated, the concourse version 3.9.2 have a lot of changes and the documentation does not provide details about it. Also the sample template for concourse manifest yml provided in step 2 is outdated.

**Comment by jncd** [comment]
@avirkar Thanks for logging this issue. Sorry that it has been open so long.
I believe that the docs were corrected a while ago:  the installation instructions are updated and the docs point to our bosh deployment repo for the most accurate and up-to-date settings.
